### ISSUE TITLE
Played with the badge a bit

### ISSUE THREAD

**Issue by bjonnh** [Hak4Kidz/H4K-badge-2019#4]
Found out that using that library makes the tft display ~20 times faster (maybe more in some cases).  Boot time including wifi connection is <1s:  https://github.com/Bodmer/TFT_eSPI

Did you had people interested in experimenting with the badge? Would having some examples (I'm toying with wifi and bluetooth for now) be useful for them?

**Comment by Hak4Kidz** [comment]
So you are saying that using the TFT_eSPI library is ~20 times faster than the Adafruit GFX library?

Some people at the event were toying with the badge. That's the beauty of an open platform. I'm hoping to hear from more people about their experiments.

Anything educational is always encouraged. So if you want to create a fork and provide your samples there, that would be cool.

Thanks,
Heal

**Comment by bjonnh** [comment]
Looks like it if not much faster. Filling the screen really feels instantaneous. I've seen reports on a ESP8266 that says 7 fold for a specific project (https://hackaday.com/2017/04/08/everyone-loves-faster-esp8266-tft-libs/). I guess I could just run the benchmark code and see. I'll keep you updated.

Ok, I'll fork and make some pull requests.

**Comment by Hak4Kidz** [comment]
Awesome! Really appreciate your help here. I'm working on some new code and this will add to the badge appeal. 

Will try out the new lib this weekend.

**Comment by Hak4Kidz** [comment]
So you know, the TFT_eSPI library was used in the DEF CON version of the firmware and it was ridiculously faster. 

https://github.com/Hak4Kidz/H4K-cryptex

Thanks for pointing me to that library!

Best,
Heal
