### ISSUE TITLE
Incorrect documentation caused board failure.

### ISSUE THREAD

**Issue by ratmandu** [Hak4Kidz/H4K-badge-2019#9]
Schematic provided in the repo shows a ST LF33 3.3v LDO regulator, which has a maximum input voltage rating of 16VDC.
Board actually has a ST LD39150 BiCMOS regulator, which has an absolute maximum input voltage of 6.5VDC.

9V was applied to the battery input on the board, and resulted in damage to the board.

I would recommend updating the documentation to note this change, so other people do not fall into the same trap of trusting the documentation provided for a product, only to be left with a dead board.

**Comment by Hak4Kidz** [comment]
Thanks for letting us know. The schematic has been updated to reflect the ST LD39150 BiCMOS regulator.

For the archive, the damaged board was replaced at GrrCON 0xA.
